version: '3.5'

services:
  backend:
    build: .
    environment:
      - DB_HOST=postgres
    volumes:
      - ./src:/usr/app/src
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres

volumes:
  postgres-db:
